version: "3"
services:
  webserver:
    build: ../../../docker/nginx/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: nginx-uwsgi-webserver
    volumes:
      - ../../../www:/www
      - ../../../script/:/script/
      - ../../../config/web-server/nginx/uwsgi/conf.d/:/etc/nginx/conf.d/
      - ../../../config/web-server/nginx/uwsgi/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../../config/web-server/nginx/uwsgi/uwsgi_params/uwsgi_params:/etc/nginx/uwsgi_params
      - ./ssl/certs/:/ssl/
      - ./ssl/letsencrypt/:/etc/letsencrypt/
      - ../../../log:/log
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "Asia/Seoul"
    restart: always

  uwsgi-app:
    build: ../../../docker/uwsgi/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: uwsgi-app
    volumes:
      - ../../../www:/www
      - ../../../config/app-server/uwsgi/uwsgi.ini:/application/uwsgi.ini
      - ../../../log:/log
    command: bash -c "pip install -r requirements.txt && uwsgi --ini /application/uwsgi.ini"
    environment:
      TZ: "Asia/Seoul"
    restart: always

  redis:
    image: redis:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: redis_db
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/:/usr/local/etc/redis/
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-stats:
    image: insready/redis-stat:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: redis-stats
    ports:
      - 63790:63790
    command: [
        '--verbose',
        '--server',
        'redis:6379',
      ]
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - redis
    restart: always
