services:
  webserver:
    build: ../../../docker/nginx/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: nginx-gunicorn-webserver
    volumes:
      - ../../../www:/www
      - ../../../script/:/script/
      - ../../../config/web-server/nginx/gunicorn/conf.d/:/etc/nginx/conf.d/
      - ../../../config/web-server/nginx/gunicorn/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../../config/web-server/nginx/gunicorn/proxy_params/proxy_params:/etc/nginx/proxy_params
      - ./ssl/certs/:/etc/ssl/certs/
      - ./ssl/letsencrypt/:/etc/letsencrypt/
      - ../../../log/:/log/
      - ../../../script/logrotate/nginx/nginx:/etc/logrotate.d/nginx
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "Asia/Seoul"
    restart: always

  gunicorn-app:
    build: ../../../docker/gunicorn/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /www/${PROJECT_DIR}
    container_name: gunicorn-app
    volumes:
      - ../../../www:/www
      - ../../../log:/log
      - ../../../config/app-server/gunicorn/:/gunicorn
      - ../../../script/logrotate/gunicorn/gunicorn:/etc/logrotate.d/gunicorn
    command: bash -c "poetry config virtualenvs.create false && poetry install --no-root --without test && gunicorn -c /gunicorn/gunicorn.conf.py"
    environment:
      TZ: "Asia/Seoul"
    restart: always

  celery:
    build: ../../../docker/gunicorn/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /www/${PROJECT_DIR}
    container_name: celery-app
    volumes:
      - ../../../www:/www
      - ../../../log:/log
      - ../../../script/logrotate/gunicorn/celery/gunicorn-celery:/etc/logrotate.d/gunicorn-celery
    command: bash -c "poetry config virtualenvs.create false && \
      poetry install --no-root && \
      celery -A config worker \
      --loglevel=INFO \
      --logfile=/log/gunicorn/celery/worker-%n%I.log "
    environment:
      TZ: "Asia/Seoul"
    restart: always
    depends_on:
      - redis
      - gunicorn-app
    profiles:
      - celery

  celery-beat:
    build: ../../../docker/gunicorn/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /www/${PROJECT_DIR}
    container_name: celerybeat-app
    volumes:
      - ../../../www:/www
      - ../../../log:/log
      - ../../../script/logrotate/gunicorn/celerybeat/gunicorn-celerybeat:/etc/logrotate.d/gunicorn-celerybeat
    command: bash -c "poetry config virtualenvs.create false && \
      poetry install --no-root && \
      celery -A config beat \
      --loglevel=INFO \
      --scheduler django_celery_beat.schedulers:DatabaseScheduler \
      --logfile=/log/gunicorn/celerybeat/celerybeat.log "
    environment:
      TZ: "Asia/Seoul"
    restart: always
    depends_on:
      - celery
    profiles:
      - celery

  flower:
    image: mher/flower:master
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_BASIC_AUTH=${FLOWER_ID}:${FLOWER_PWD}
    restart: always
    depends_on:
      - celery-beat
    profiles:
      - celery

  redis:
    image: redis:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: redis_db
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/:/usr/local/etc/redis/
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-stats:
    image: insready/redis-stat:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: redis-stats
    ports:
      - 63790:63790
    command: ["--verbose", "--server", "redis:6379"]
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - redis
    restart: always
    profiles:
      - redis
