version: "3"
services:
  webserver:
    image: nginx:latest    
    container_name: nginx-webserver      
    volumes:
      - ../../config/sites-available/:/etc/nginx/sites-available/
      - ../../config/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../www:/www
      - ../../config/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params        
      - ../../nginx_cache/:/etc/nginx/cache/
      - ../../ssl:/etc/nginx/ssl/
      - ../../log/nginx/:/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    restart: always    
    depends_on:
      - app
      - openproject

  app:
    build: ../../docker/php-fpm/
    working_dir: /application
    container_name: php-fpm7.3      
    volumes:
        - ../../www/:/www/
        - ../../config/pool.d/:/etc/php/7.3/fpm/pool.d
        - ../../config/php_ini/php.ini:/etc/php/7.3/fpm/php.ini        
    restart: always

  openproject:
    image: openproject/community:latest
    container_name: openproject
    environment:
      EMAIL_DELIVERY_METHOD: smtp
      SMTP_ADDRESS: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_DOMAIN: "domain"
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_USER_NAME: "id"
      SMTP_PASSWORD: "api key"
    volumes:
      - ./pgdata/:/var/openproject/pgdata/
      - ../../log/supervisor/:/var/log/supervisor/
      - ./static/:/var/openproject/assets/
    expose:
      - "8080"   
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      TZ: "Asia/Seoul"
      
  tizenenv:
    build: ../../docker/tizen-env/
    container_name: tizenenv
    volumes:
      - ../../log/tizen/:/log/tizen/
    environment:
      TZ: "Asia/Seoul"      
    restart: always