version: "3"
services:
  openproject:
    image: openproject/community:latest
    container_name: openproject
    environment:
      EMAIL_DELIVERY_METHOD: smtp
      SMTP_ADDRESS: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_DOMAIN: "domain"
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_USER_NAME: "id"
      SMTP_PASSWORD: "api key"
    volumes:
      - ./pgdata/:/var/openproject/pgdata/
      - ../../log/supervisor/:/var/log/supervisor/
      - ./static/:/var/openproject/assets/
    expose:
      - "8080"
    restart: always

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ../../config/sites-available/:/etc/nginx/sites-available/
      - ../../config/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../config/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
      - ../../nginx_cache/:/etc/nginx/cache/
      - ../../ssl:/etc/nginx/ssl/
      - ../../log/nginx/:/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - openproject
