services:
  webserver:
    build: ../../docker/nginx/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: nginx-webserver
    volumes:
      - ../../www:/www
      - ../../script/:/script/
      - ../../bin/certbot-auto:/usr/local/bin/certbot-auto
      - ../../config/web-server/nginx/php/conf.d/:/etc/nginx/conf.d/
      - ../../config/web-server/nginx/php/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../config/web-server/nginx/php/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
      - ../../config/web-server/nginx/php/proxy_params/proxy_params:/etc/nginx/proxy_params
      - ./ssl/certs/:/etc/ssl/certs/
      - ./ssl/letsencrypt/:/etc/letsencrypt/
      - ../../log/:/log/
      - ../../script/logrotate/nginx/nginx:/etc/logrotate.d/nginx
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "Asia/Seoul"
    restart: always
    depends_on:
      - php-app
      - openproject
      - jenkins

  php-app:
    build: ../../docker/php-fpm/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: php-app
    volumes:
      - ../../www/:/www/
      - ../../config/app-server/php/pool.d/:/etc/php/7.3/fpm/pool.d
      - ../../config/app-server/php/php_ini/php.ini:/etc/php/7.3/fpm/php.ini
      - ../../log:/log
      - ../../script/logrotate/php-fpm/php-fpm:/etc/logrotate.d/php-fpm
    environment:
      TZ: "Asia/Seoul"
    restart: always

  redis:
    image: redis:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: redis_db
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/:/usr/local/etc/redis/
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    profiles:
      - redis

  redis-stats:
    image: insready/redis-stat:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: redis-stats
    ports:
      - 63790:63790
    command: ["--verbose", "--server", "redis:6379"]
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - redis
    restart: always
    profiles:
      - redis

  openproject:
    image: openproject/community:11
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: openproject
    privileged: true
    volumes:
      - ./pgdata/:/var/openproject/pgdata/
      - ../../log/supervisor/:/var/log/supervisor/
      - ./static/:/var/openproject/assets/
    expose:
      - 8080
    environment:
      EMAIL_DELIVERY_METHOD: ${EMAIL_DELIVERY_METHOD}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: "${SMTP_DOMAIN}"
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: "${SMTP_ENABLE_STARTTLS_AUTO}"
      SMTP_USER_NAME: "${SMTP_USER_NAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      TZ: "Asia/Seoul"
      PASSENGER_START_TIMEOUT: ${PASSENGER_START_TIMEOUT}
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: jenkins
    privileged: true
    volumes:
      - ./jenkins_home:/var/jenkins_home
    expose:
      - 8080
    environment:
      TZ: "Asia/Seoul"
    restart: always

  gitolite:
    build: ../../docker/gitolite
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: gitolite
    volumes:
      - ./storage:/home/gitolite-creator/repositories
    ports:
      - 2222:22
    environment:
      TZ: "Asia/Seoul"
    restart: always

  tizenenv:
    build: ../../docker/tizen-env/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: tizenenv
    privileged: true
    volumes:
      - ../../log/tizen/:/log/tizen/
    ports:
      - 2221:22
    environment:
      TZ: "Asia/Seoul"
    restart: always
