version: "3"
services:
  webserver:
    image: nginx:latest    
    container_name: nginx-webserver      
    volumes:
      - ../../www:/www
      - ../../script/:/script/
      - ../../bin/certbot-auto:/usr/local/bin/certbot-auto
      - ../../config/web-server/nginx/php/sites-available/:/etc/nginx/sites-available/
      - ../../config/web-server/nginx/php/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../config/web-server/nginx/php/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
      - ../../nginx_cache/:/etc/nginx/cache/
      - ../../ssl/letsencrypt/:/etc/letsencrypt/
      - ../../ssl/ssl/:/etc/ssl/
      - ../../ssl/nginx/:/etc/nginx/ssl/
      - ../../log/nginx/:/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Seoul"
    restart: always    
    depends_on:
      - app
      - openproject

  app:
    build: ../../docker/php-fpm/
    working_dir: /application
    container_name: php-fpm7.3      
    volumes:
      - ../../www/:/www/
      - ../../config/app-server/php/pool.d/:/etc/php/7.3/fpm/pool.d
      - ../../config/app-server/php/php_ini/php.ini:/etc/php/7.3/fpm/php.ini
    environment:
      TZ: "Asia/Seoul"
    restart: always

  openproject:
    image: openproject/community:latest
    container_name: openproject
    environment:
      EMAIL_DELIVERY_METHOD: smtp
      SMTP_ADDRESS: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_DOMAIN: "domain"
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_USER_NAME: "id"
      SMTP_PASSWORD: "api key"
    volumes:
      - ./pgdata/:/var/openproject/pgdata/
      - ../../log/supervisor/:/var/log/supervisor/
      - ./static/:/var/openproject/assets/
    expose:
      - "8080"   
    environment:
      TZ: "Asia/Seoul"
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins    
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      TZ: "Asia/Seoul"
    restart: always
